### ISSUE TITLE
is it vac safe?

### ISSUE THREAD

**Issue by gagandeep1994** [labo89/owdl#2]
is it safe? i mean i don't wana lose my prime acc 150 wins
and can you tell steps also like do i have to start the .exe first after that i have to download demo and it will show?
i also wanted to know do i have to start the program again after every ow case or do i have to leave it open?

**Comment by hexadezi** [comment]
It does not interact with the csgo.exe. It just monitors the traffic. So it should be safe.
First install Npcap. Then start owdl and download the evidence in csgo. It will download the demo and extract to the desktop.
